### ISSUE TITLE
Add Router system using go_router

### ISSUE THREAD

**Issue by call-me-q** [call-me-q/zikr#6]
Flutter has a good router (at least the way I know it). use `go_router` and implement it.

**Comment by call-me-q** [comment]
added in 1637ca2087cb2c3c0df9ac241e83599957f5824d

**Comment by sidputamim-png** [comment]
![Image](https://github.com/user-attachments/assets/5eb70630-0774-41ca-b6d4-5444c0183c37)

**Comment by sidputamim-png** [comment]
![Image](https://github.com/user-attachments/assets/0f2548b1-f806-490d-a418-963ac5e0e6d7)

**Comment by sidputamim-png** [comment]
![Image](https://github.com/user-attachments/assets/84010d13-5a27-46a9-bc3f-4d08fa514e8d)

>

**Comment by sidputamim-png** [comment]
![Image](https://github.com/user-attachments/assets/92de9395-23bf-48a5-a215-aabbdb86b324)

**Comment by sidputamim-png** [comment]
![Image](https://github.com/user-attachments/assets/78e424f1-ecb7-4613-9ff2-ba8e3516a481)

**Comment by sidputamim-png** [comment]
![Image](https://github.com/user-attachments/assets/4b720965-b648-4dc3-a263-c9fabd4d0a7a)
![Image](https://github.com/user-attachments/assets/75f20bcf-83f1-4bf3-8f90-f44aaec651d5)

**Comment by sidputamim-png** [comment]
![Image](https://github.com/user-attachments/assets/79b05a16-9991-4997-a8ce-c8e31af82961)

**Comment by sidputamim-png** [comment]
<html><head></head><body><div style="font-weight: 400; overflow-wrap: break-word; margin: 16px 0;">A <span style="font-weight: bold;">command bot</span> is <mark style="font-weight: bold; background: #D3E3FD;">a software application designed to execute specific, predefined tasks in response to direct text inputs, often called "commands"</mark>. Unlike conversational chatbots that mimic human dialogue, command bots typically follow a strict "instruction-and-response" model. [1, 2, 3, 4] </div><h2 style="font-size: 20px; font-weight: 600;" role="heading">Core Functionality</h2><div><div></div><ul><li><span style="font-weight: bold;">Trigger Mechanism:</span> Users initiate actions by typing specific strings, often starting with a prefix like a forward slash (e.g., <code dir="ltr" style="background-color: #f4f6f7; border: 1px solid #f4f6f7; border-radius: 4px; padding: 2px 4px;">/start</code>) or a symbol (e.g., <code dir="ltr" style="background-color: #f4f6f7; border: 1px solid #f4f6f7; border-radius: 4px; padding: 2px 4px;">!help</code>).</li><li><span style="font-weight: bold;">Automation:</span> They are primarily used to automate repetitive tasks, such as checking a ticket status, retrieving information, or managing group permissions.</li><li><span style="font-weight: bold;">Structured Interaction:</span> Modern command bots frequently use UI elements like <span style="font-weight: bold;">Slash Commands</span>, menus, or "Adaptive Cards" to provide a cleaner user experience than plain text. [1, 5, 6, 7, 8] </li></ul></div><h2 style="font-size: 20px; font-weight: 600;" role="heading">Common Platforms and Examples</h2><div><div></div><ul><li><span style="font-weight: bold;">Discord:</span> Uses slash commands (e.g., <code dir="ltr" style="background-color: #f4f6f7; border: 1px solid #f4f6f7; border-radius: 4px; padding: 2px 4px;">/ping</code>) to provide auto-suggestions and descriptions for bot functions.</li><li><span style="font-weight: bold;">Slack:</span> Features slash commands like <code dir="ltr" style="background-color: #f4f6f7; border: 1px solid #f4f6f7; border-radius: 4px; padding: 2px 4px;">/weather</code> or <code dir="ltr" style="background-color: #f4f6f7; border: 1px solid #f4f6f7; border-radius: 4px; padding: 2px 4px;">/todo</code> that send a data payload to a specific URL for processing.</li><li><span style="font-weight: bold;">Telegram:</span> Employs a command system where users can see a list of available actions by typing <code dir="ltr" style="background-color: #f4f6f7; border: 1px solid #f4f6f7; border-radius: 4px; padding: 2px 4px;">/</code>.</li><li><span style="font-weight: bold;">Microsoft Teams:</span> Utilizes command bots to display UI components in response to simple chat triggers. [1, 6, 9, 10, 11] </li></ul></div><h2 style="font-size: 20px; font-weight: 600;" role="heading">Command Bot vs. Chatbot</h2>
Feature [1, 3, 4, 5, 12, 13] | Command Bot | Chatbot
-- | -- | --
Logic | Rule-based (If "X", do "Y") | Conversational/AI-driven
Input | Strict commands/prefixes | Natural language
Goal | Task execution | Simulating human interaction

<div style="font-weight: 400; overflow-wrap: break-word; margin: 16px 0;"><span style="font-weight: bold;">Security Note:</span> In cybersecurity, "Command and Control" (C2) refers to malicious bots that receive instructions from a central server to perform attacks like DDoS or data theft. [14, 15] </div><div style="font-weight: 400; overflow-wrap: break-word; margin: 16px 0;">Are you looking to <span style="font-weight: bold;">build</span> a command bot for a specific platform like <span style="font-weight: bold;">Discord</span> or <span style="font-weight: bold;">Slack</span>?</div><div><br><div>[1] <a href="https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/command-bot-in-teams">https://learn.microsoft.com</a></div><div>[2] <a href="https://www.ionos.com/digitalguide/online-marketing/online-sales/what-is-a-bot/">https://www.ionos.com</a></div><div>[3] <a href="https://www.callcentrehelper.com/difference-between-bot-and-chatbot-205949.htm">https://www.callcentrehelper.com</a></div><div>[4] <a href="https://www.crescendo.ai/blog/bots-vs-chatbots-vs-ai-agents-vs-ai-assistants">https://www.crescendo.ai</a></div><div>[5] <a href="https://telegram-bot-sdk.com/docs/guides/commands-system/">https://telegram-bot-sdk.com</a></div><div>[6] <a href="https://arjancodes.com/blog/how-to-build-a-simple-discord-bot/">https://arjancodes.com</a></div><div>[7] <a href="https://techterms.com/definition/bot">https://techterms.com</a></div><div>[8] <a href="https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu">https://learn.microsoft.com</a></div><div>[9] <a href="https://support.discord.com/hc/en-us/articles/31232432266647-Discord-Commands-Shortcuts-and-Navigation-Guide">https://support.discord.com</a></div><div>[10] <a href="https://docs.slack.dev/interactivity/implementing-slash-commands/">https://docs.slack.dev</a></div><div>[11] <a href="https://docs.bird.com/applications/channels/channels/supported-channels/telegram/bot-commands-setup">https://docs.bird.com</a></div><div>[12] <a href="https://devrev.ai/blog/chatbots-vs-conversational-ai">https://devrev.ai</a></div><div>[13] <a href="https://www.dictionary.com/browse/bot">https://www.dictionary.com</a></div><div>[14] <a href="https://trainingcamp.com/glossary/bot-command-and-control/">https://trainingcamp.com</a></div><div>[15] <a href="https://www.akamai.com/glossary/what-is-a-bot">https://www.akamai.com</a></div></div></body></html>A command bot is a software application designed to execute specific, predefined tasks in response to direct text inputs, often called "commands". Unlike conversational chatbots that mimic human dialogue, command bots typically follow a strict "instruction-and-response" model. [1, 2, 3, 4] 
Core Functionality

* Trigger Mechanism: Users initiate actions by typing specific strings, often starting with a prefix like a forward slash (e.g., /start) or a symbol (e.g., !help).
* Automation: They are primarily used to automate repetitive tasks, such as checking a ticket status, retrieving information, or managing group permissions.
* Structured Interaction: Modern command bots frequently use UI elements like Slash Commands, menus, or "Adaptive Cards" to provide a cleaner user experience than plain text. [1, 5, 6, 7, 8] 

Common Platforms and Examples

* Discord: Uses slash commands (e.g., /ping) to provide auto-suggestions and descriptions for bot functions.
* Slack: Features slash commands like /weather or /todo that send a data payload to a specific URL for processing.
* Telegram: Employs a command system where users can see a list of available actions by typing /.
* Microsoft Teams: Utilizes command bots to display UI components in response to simple chat triggers. [1, 6, 9, 10, 11] 

Command Bot vs. Chatbot

| Feature [1, 3, 4, 5, 12, 13] | Command Bot | Chatbot |
|---|---|---|
| Logic | Rule-based (If "X", do "Y") | Conversational/AI-driven |
| Input | Strict commands/prefixes | Natural language |
| Goal | Task execution | Simulating human interaction |

Security Note: In cybersecurity, "Command and Control" (C2) refers to malicious bots that receive instructions from a central server to perform attacks like DDoS or data theft. [14, 15] 
Are you looking to build a command bot for a specific platform like Discord or Slack?

[1] [[https://learn.microsoft.com](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/command-bot-in-teams)](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/command-bot-in-teams)
[2] [[https://www.ionos.com](https://www.ionos.com/digitalguide/online-marketing/online-sales/what-is-a-bot/)](https://www.ionos.com/digitalguide/online-marketing/online-sales/what-is-a-bot/)
[3] [[https://www.callcentrehelper.com](https://www.callcentrehelper.com/difference-between-bot-and-chatbot-205949.htm)](https://www.callcentrehelper.com/difference-between-bot-and-chatbot-205949.htm)
[4] [[https://www.crescendo.ai](https://www.crescendo.ai/blog/bots-vs-chatbots-vs-ai-agents-vs-ai-assistants)](https://www.crescendo.ai/blog/bots-vs-chatbots-vs-ai-agents-vs-ai-assistants)
[5] [[https://telegram-bot-sdk.com](https://telegram-bot-sdk.com/docs/guides/commands-system/)](https://telegram-bot-sdk.com/docs/guides/commands-system/)
[6] [[https://arjancodes.com](https://arjancodes.com/blog/how-to-build-a-simple-discord-bot/)](https://arjancodes.com/blog/how-to-build-a-simple-discord-bot/)
[7] [[https://techterms.com](https://techterms.com/definition/bot)](https://techterms.com/definition/bot)
[8] [[https://learn.microsoft.com](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu)](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-commands-menu)
[9] [[https://support.discord.com](https://support.discord.com/hc/en-us/articles/31232432266647-Discord-Commands-Shortcuts-and-Navigation-Guide)](https://support.discord.com/hc/en-us/articles/31232432266647-Discord-Commands-Shortcuts-and-Navigation-Guide)
[10] [[https://docs.slack.dev](https://docs.slack.dev/interactivity/implementing-slash-commands/)](https://docs.slack.dev/interactivity/implementing-slash-commands/)
[11] [[https://docs.bird.com](https://docs.bird.com/applications/channels/channels/supported-channels/telegram/bot-commands-setup)](https://docs.bird.com/applications/channels/channels/supported-channels/telegram/bot-commands-setup)
[12] [[https://devrev.ai](https://devrev.ai/blog/chatbots-vs-conversational-ai)](https://devrev.ai/blog/chatbots-vs-conversational-ai)
[13] [[https://www.dictionary.com](https://www.dictionary.com/browse/bot)](https://www.dictionary.com/browse/bot)
[14] [[https://trainingcamp.com](https://trainingcamp.com/glossary/bot-command-and-control/)](https://trainingcamp.com/glossary/bot-command-and-control/)
[15] [[https://www.akamai.com](https://www.akamai.com/glossary/what-is-a-bot)](https://www.akamai.com/glossary/what-is-a-bot)
